name: Android CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x ./Project/gradlew
    - name: Run all unit tests
      run: ./gradlew test --stacktrace
      working-directory: ./Project
 
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x ./Project/gradlew
    - name: Build the project
      run: ./gradlew build --stacktrace
      working-directory: ./Project
      
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradlew executable
      run: chmod +x ./Project/gradlew
    - name: Generate APK
      run: ./gradlew assemble --stacktrace
      working-directory: ./Project
      
    - name: Upload APK to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: Project/app/build/outputs/apk/debug/app-debug.apk
