name: Android CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Unit tests
      run: ./Project/gradlew test --stacktrace
 
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: ./Project/gradlew build --stacktrace
      
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: APK
        run: ./Project/gradlew assemble --stacktrace
      
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: Project/app/build/outputs/apk/debug/app-debug.apk
